### 1.	Write a program to take a name and age from the user and print a greeting message.

In [3]:
user_name = input("Enter your Name")
user_age  = input("Enter your Age")
print(f"Good morning {user_name} and My Age is {user_age}")

Enter your Name Sivani
Enter your Age 21

Good morning Sivani and My Age is 21

### 2.Create a list of numbers and print only even numbers using a for loop.

In [5]:
even_numbers =[]
numbers = range(1,80)
for i in numbers:
    if i%2==0:
        even_numbers.append(i)
print(even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78]

### 3.Write a program that handles division by zero using try-except.

In [7]:
num = int(input("Enter Numerator:"))
den = int(input("Enter Denominator:"))
try:
    answer = num/den
    print(answer)
except ZeroDivisionError:
    print("Error:Cannot divided by Zero.")

Enter Numerator: 8
Enter Denominator: 0

Error:Cannot divided by Zero.

### 4.Given a string, count how many vowels it has.

In [12]:
user_input = input("Enter any Word or Sentence:")
count = 0
for i in user_input.lower():
    if i in "aeiou":
        count+=1
print("Total Number of vowels are:",count)

Enter any Word or Sentence: Good Morning Eswari

Total Number of vowels are: 7

### 5.Reverse a list without using built-in reverse functions.

In [13]:
original_list = [1,2,3,4,5]
updated_list =[]
i = len(original_list)-1
while i>=0:
    updated_list.append(original_list[i])
    i=i-1
updated_list

[5, 4, 3, 2, 1]

### 6.Create a dictionary with at least 5 key-value pairs and print them.

In [1]:
import pandas as pd

In [2]:

Shop_data = {"Product ":["Soap","Shampoo","Brush","Cake"],"price":[50,150,30,25],"Stock":[100,90,50,20],"Brand":["Lux","Meera","Colgate","Britannia"],"Category":["Bath","Hair","Dental","Food"]}
data_frame1 = pd.DataFrame(Shop_data)
data_frame1

  Product   price  Stock      Brand Category
0     Soap     50    100        Lux     Bath
1  Shampoo    150     90      Meera     Hair
2    Brush     30     50    Colgate   Dental
3     Cake     25     20  Britannia     Food

### 7.Write a Pandas code to read a CSV and print the top 5 rows.

In [4]:
pd.read_csv("employee_data.csv").head()

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024

### 8.Create a DataFrame from a Python dictionary.

In [5]:
import pandas as pd
Employee_data = {"Emp_ID":[4,6,8],"Age":[23,24,25],"Name":["Raji","Lata","ravi"],"salary":[35000,45000,38000]}
data_frame2 = pd.DataFrame(Employee_data)
data_frame2

   Emp_ID  Age  Name  salary
0       4   23  Raji   35000
1       6   24  Lata   45000
2       8   25  ravi   38000

### 9.Replace all missing values in a DataFrame with the column’s mean.

In [7]:
employee_data = pd.read_csv("employee_data.csv")
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [9]:
employee_data["Salary"].mean()

np.float64(62500.0)

In [11]:
employee_data["Salary"].fillna(value = employee_data["Salary"].mean(),inplace = True)

In [12]:
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

### 10.Filter rows in a DataFrame where the "Age" column is greater than 30.

In [13]:
employee_data[employee_data["Age"]>30]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech  62500.0  12-11-2020
5  Navin  35.0    Support  72000.0  19-08-2023
6    NaN  40.0         IT  64000.0  10-09-2022
7  Nasir  31.0    IT Tech  62500.0  12-11-2020